version: '3'

services:
  flask-server:
    build: ./flask-server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - common-network

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - flask-server
    networks:
      - common-network

networks:
  common-network:
    driver: bridge